[package]
name = "rinha-fraud"
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

[dependencies]
libc = "0.2"
sha2 = "0.10"
tokio = { version = "1.43", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
