services:
  lb:
    image: haproxy:2.9-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - backend-sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "${LB_CPUS:-0.20}"
          memory: "32MB"

  api1:
    image: ghcr.io/daniloitagyba/rinha-2026-rust:latest
    platform: linux/amd64
    environment:
      BIND_ADDR: unix:/sockets/api1.sock
      INDEX_PATH: /app/data/references.idx
      PREFETCH_INDEX: "true"
      WORKERS: "${API_WORKERS:-2}"
      KEEP_ALIVE_REQUESTS: "${KEEP_ALIVE_REQUESTS:-256}"
      EARLY_CANDIDATES: "16200"
      MIN_CANDIDATES: "16200"
      MAX_CANDIDATES: "32400"
      PROFILE_FASTPATH: "1"
      PROFILE_MIN_COUNT: "20"
      EXACT_FALLBACK: "risky"
      FAST_PATH: "false"
    volumes:
      - backend-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API_CPUS:-0.40}"
          memory: "156MB"

  api2:
    image: ghcr.io/daniloitagyba/rinha-2026-rust:latest
    platform: linux/amd64
    environment:
      BIND_ADDR: unix:/sockets/api2.sock
      INDEX_PATH: /app/data/references.idx
      PREFETCH_INDEX: "true"
      WORKERS: "${API_WORKERS:-2}"
      KEEP_ALIVE_REQUESTS: "${KEEP_ALIVE_REQUESTS:-256}"
      EARLY_CANDIDATES: "16200"
      MIN_CANDIDATES: "16200"
      MAX_CANDIDATES: "32400"
      PROFILE_FASTPATH: "1"
      PROFILE_MIN_COUNT: "20"
      EXACT_FALLBACK: "risky"
      FAST_PATH: "false"
    volumes:
      - backend-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API_CPUS:-0.40}"
          memory: "156MB"

volumes:
  backend-sockets:
